version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - appnet

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - appnet

networks:
  appnet: